name: Daily Repository Update

on:
  schedule:
    - cron: "30 2 * * *"  # Runs daily at 02:30 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Git Config (harshkumar.prasad@straive.com)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "harshkumar.prasad@straive.com"

      - name: Create or Update a File
        run: |
          echo "Last update: $(date)" > daily_update.txt
          git add daily_update.txt
          git commit -m "Automated daily update - $(date)"
          git push

      - name: Confirm Commit
        run: git log -1
